#\u5728coupon\u9879\u76EE\u7684resources\u76EE\u5F55\u4E0B\u65B0\u5EFAapplication.yml
server:
  port: 8005
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.61.138.205:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware
# MapperScan
# sql\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto


